### ISSUE TITLE
The pre-trained model of "model_noresqa_mos.pth" can not be successfully loaded.

### ISSUE THREAD

**Issue by xiaoyiming** [facebookresearch/Noresqa#8] opened 2022-10-28 02:14 UTC
>>> model_checkpoint_path = 'models/model_noresqa_mos.pth'
>>> state = torch.load(model_checkpoint_path,map_location="cpu")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\xymtest2\lib\site-packages\torch\serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\ProgramData\Anaconda3\envs\xymtest2\lib\site-packages\torch\serialization.py", line 763, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by argxkr** [comment] 2022-10-28 04:13
I am not able to reproduce this error. What us the pytorch version you are using ? We have tested with 1.12.0 and loading works.

**Comment by xiaoyiming** [comment] 2022-10-28 04:19
> I am not able to reproduce this error. What us the pytorch version you are using ? We have tested with 1.12.0 and loading works.

Thanks, my torch version is 1.7.0.  I will try with 1.12.0

**Comment by xiaoyiming** [comment] 2022-10-28 07:59
> I am not able to reproduce this error. What us the pytorch version you are using ? We have tested with 1.12.0 and loading works.

It seems that there is a problem with the uploaded pre-training file, please check whether the complete file has been uploaded
![image](https://user-images.githubusercontent.com/34536740/198535728-7b11f19c-9048-42a3-9c75-a8f5c2a5e87a.png)

**Comment by argxkr** [comment] 2022-10-28 23:17
I think cloning with git lfs should work. I am closing this issue for now.

**Closed by argxkr** 2022-10-28 23:17 UTC
